apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../global

patches:
- patch: |-
    - op: replace
      path: /spec/destination/name
      value: test-2
    - op: replace
      path: /metadata/name
      value: atlantis-dev-1
  target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: atlantis
